//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.WsDatos {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/wsConsultaDatosCarga/ServicioDatos", ConfigurationName="WsDatos.ServicioDatosSoap")]
    public interface ServicioDatosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsConsultaDatosCarga/ServicioDatos/ObtenerRutaAlmacenamientoEC" +
            "M", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ObtenerRutaAlmacenamientoECM(string pvarCodAlmacenamiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsConsultaDatosCarga/ServicioDatos/ObtenerRutaAlmacenamientoEC" +
            "M", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ObtenerRutaAlmacenamientoECMAsync(string pvarCodAlmacenamiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsConsultaDatosCarga/ServicioDatos/EjecutaConsulta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet EjecutaConsulta(string pvarAplicaion, string pvarConexion, string pvarStoreProcedure, string pvarParametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsConsultaDatosCarga/ServicioDatos/EjecutaConsulta", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> EjecutaConsultaAsync(string pvarAplicaion, string pvarConexion, string pvarStoreProcedure, string pvarParametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsConsultaDatosCarga/ServicioDatos/EjecutaConsultaDt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EjecutaConsultaDt(string pvarAplicaion, string pvarConexion, string pvarStoreProcedure, string pvarParametros, System.Data.DataTable pvarParametrosdt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsConsultaDatosCarga/ServicioDatos/EjecutaConsultaDt", ReplyAction="*")]
        System.Threading.Tasks.Task<string> EjecutaConsultaDtAsync(string pvarAplicaion, string pvarConexion, string pvarStoreProcedure, string pvarParametros, System.Data.DataTable pvarParametrosdt);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioDatosSoapChannel : Dashboard.WsDatos.ServicioDatosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioDatosSoapClient : System.ServiceModel.ClientBase<Dashboard.WsDatos.ServicioDatosSoap>, Dashboard.WsDatos.ServicioDatosSoap {
        
        public ServicioDatosSoapClient() {
        }
        
        public ServicioDatosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioDatosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDatosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDatosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ObtenerRutaAlmacenamientoECM(string pvarCodAlmacenamiento) {
            return base.Channel.ObtenerRutaAlmacenamientoECM(pvarCodAlmacenamiento);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerRutaAlmacenamientoECMAsync(string pvarCodAlmacenamiento) {
            return base.Channel.ObtenerRutaAlmacenamientoECMAsync(pvarCodAlmacenamiento);
        }
        
        public System.Data.DataSet EjecutaConsulta(string pvarAplicaion, string pvarConexion, string pvarStoreProcedure, string pvarParametros) {
            return base.Channel.EjecutaConsulta(pvarAplicaion, pvarConexion, pvarStoreProcedure, pvarParametros);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> EjecutaConsultaAsync(string pvarAplicaion, string pvarConexion, string pvarStoreProcedure, string pvarParametros) {
            return base.Channel.EjecutaConsultaAsync(pvarAplicaion, pvarConexion, pvarStoreProcedure, pvarParametros);
        }
        
        public string EjecutaConsultaDt(string pvarAplicaion, string pvarConexion, string pvarStoreProcedure, string pvarParametros, System.Data.DataTable pvarParametrosdt) {
            return base.Channel.EjecutaConsultaDt(pvarAplicaion, pvarConexion, pvarStoreProcedure, pvarParametros, pvarParametrosdt);
        }
        
        public System.Threading.Tasks.Task<string> EjecutaConsultaDtAsync(string pvarAplicaion, string pvarConexion, string pvarStoreProcedure, string pvarParametros, System.Data.DataTable pvarParametrosdt) {
            return base.Channel.EjecutaConsultaDtAsync(pvarAplicaion, pvarConexion, pvarStoreProcedure, pvarParametros, pvarParametrosdt);
        }
    }
}
